-- sido 데이터 생성(기본키, 디폴트값, 널여부 설정을 위해 별도의 테이블 생성 ddl 필요)
--create table sido as
--select rownum as sido_no, a.sido sido_nm
--  from (select distinct sido 
--          from ziptb) a;

select count(*) from (select distinct gugun, sido from ziptb);

select count(*) 
  from (select distinct gugun from ziptb);

select rownum as gugun a.gugun          
from (select distinct gugun, sido 
        from ziptb
       order by sido) a

--create or replace view v_templete as
--select distinct gugun, sido from ziptb order by sido
--with read only;

select * from v_templete;

-- gugun 데이터 생성(기본키, 디폴트값, 널여부 설정을 위해 별도의 테이블 생성 ddl 필요)
--create or replace view v_templete as
--select b.gugun, b.sido, a.sido_no
--  from sido a
-- inner join (select distinct gugun, sido from ziptb order by sido) b on ( a.sido_nm = b.sido)
-- order by 3, 1
--  with read only;

select * from v_templete;

select b.gugun, b.sido, a.sido_no
  from sido a
 inner join v_templete b on ( a.sido_nm = b.sido)
 order by 3, 1

select distinct gugun from ziptb

CREATE TABLE GUGUN 
(
  SIDO_NO NUMBER NOT NULL 
, GUGUN_NO NUMBER NOT NULL 
, GUGUN_NM VARCHAR2(30) 
, CONSTRAINT GUGUN_PK PRIMARY KEY 
  (
    SIDO_NO 
  , GUGUN_NO 
  )
  ENABLE 
);


INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '1', '강남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '2', '강동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '3', '강북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '4', '강서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '5', '관악구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '6', '광진구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '7', '구로구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '8', '금천구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '9', '노원구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '10', '도봉구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '11', '동대문구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '12', '동작구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '13', '마포구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '14', '서대문구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '15', '서초구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '16', '성동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '17', '성북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '18', '송파구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '19', '양천구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '20', '영등포구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '21', '용산구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '22', '은평구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '23', '종로구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '24', '중구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('1', '25', '중랑구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '1', '계룡시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '2', '공주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '3', '금산군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '4', '논산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '5', '당진시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '6', '보령시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '7', '부여군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '8', '서산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '9', '서천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '10', '아산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '11', '예산군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '12', '천안시 동남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '13', '천안시 서북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '14', '청양군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '15', '태안군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('2', '16', '홍성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '1', '강서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '2', '금정구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '3', '기장군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '4', '남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '5', '동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '6', '동래구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '7', '부산진구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '8', '북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '9', '사상구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '10', '사하구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '11', '서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '12', '수영구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '13', '연제구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '14', '영도구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '15', '중구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('3', '16', '해운대구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '1', '강화군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '2', '계양구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '3', '남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '4', '남동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '5', '동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '6', '부평구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '7', '서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '8', '연수구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '9', '옹진군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('4', '10', '중구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('5', '1', '남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('5', '2', '동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('5', '3', '북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('5', '4', '울주군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('5', '5', '중구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('6', '1', '서귀포시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('6', '2', '제주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('7', '1', '광산구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('7', '2', '남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('7', '3', '동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('7', '4', '북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('7', '5', '서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('8', '1', '대덕구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('8', '2', '동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('8', '3', '서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('8', '4', '유성구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('8', '5', '중구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '1', '남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '2', '달서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '3', '달성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '4', '동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '5', '북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '6', '서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '7', '수성구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('9', '8', '중구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '1', '강릉시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '2', '고성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '3', '동해시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '4', '삼척시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '5', '속초시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '6', '양구군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '7', '양양군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '8', '영월군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '9', '원주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '10', '인제군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '11', '정선군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '12', '철원군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '13', '춘천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '14', '태백시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '15', '평창군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '16', '홍천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '17', '화천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('10', '18', '횡성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '1', '경산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '2', '경주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '3', '고령군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '4', '구미시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '5', '군위군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '6', '김천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '7', '문경시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '8', '봉화군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '9', '상주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '10', '성주군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '11', '안동시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '12', '영덕군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '13', '영양군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '14', '영주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '15', '영천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '16', '예천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '17', '울릉군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '18', '울진군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '19', '의성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '20', '청도군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '21', '청송군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '22', '칠곡군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '23', '포항시 남구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('11', '24', '포항시 북구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '1', '고창군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '2', '군산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '3', '김제시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '4', '남원시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '5', '무주군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '6', '부안군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '7', '순창군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '8', '완주군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '9', '익산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '10', '임실군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '11', '장수군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '12', '전주시 덕진구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '13', '전주시 완산구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '14', '정읍시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('12', '15', '진안군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '1', '강진군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '2', '고흥군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '3', '곡성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '4', '광양시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '5', '구례군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '6', '나주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '7', '담양군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '8', '목포시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '9', '무안군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '10', '보성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '11', '순천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '12', '신안군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '13', '여수시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '14', '영광군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '15', '영암군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '16', '완도군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '17', '장성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '18', '장흥군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '19', '진도군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '20', '함평군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '21', '해남군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('13', '22', '화순군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '1', '가평군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '2', '고양시 덕양구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '3', '고양시 일산동구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '4', '고양시 일산서구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '5', '과천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '6', '광명시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '7', '광주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '8', '구리시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '9', '군포시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '10', '김포시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '11', '남양주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '12', '동두천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '13', '부천시 소사구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '14', '부천시 오정구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '15', '부천시 원미구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '16', '성남시 분당구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '17', '성남시 수정구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '18', '성남시 중원구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '19', '수원시 권선구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '20', '수원시 영통구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '21', '수원시 장안구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '22', '수원시 팔달구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '23', '시흥시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '24', '안산시 단원구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '25', '안산시 상록구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '26', '안성시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '27', '안양시 동안구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '28', '안양시 만안구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '29', '양주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '30', '양평군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '31', '여주군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '32', '연천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '33', '오산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '34', '용인시 기흥구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '35', '용인시 수지구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '36', '용인시 처인구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '37', '의왕시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '38', '의정부시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '39', '이천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '40', '파주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '41', '평택시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '42', '포천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '43', '하남시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('14', '44', '화성시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '1', '거제시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '2', '거창군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '3', '고성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '4', '김해시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '5', '남해군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '6', '밀양시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '7', '사천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '8', '산청군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '9', '양산시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '10', '의령군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '11', '진주시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '12', '창녕군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '13', '창원시 마산합포구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '14', '창원시 마산회원구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '15', '창원시 성산구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '16', '창원시 의창구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '17', '창원시 진해구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '18', '통영시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '19', '하동군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '20', '함안군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '21', '함양군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('15', '22', '합천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('16', '1', '세종시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '1', '괴산군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '2', '단양군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '3', '보은군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '4', '영동군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '5', '옥천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '6', '음성군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '7', '제천시');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '8', '증평군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '9', '진천군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '10', '청원군');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '11', '청주시 상당구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '12', '청주시 흥덕구');
INSERT INTO "CODE_PEOPLE"."GUGUN" (SIDO_NO, GUGUN_NO, GUGUN_NM) VALUES ('17', '13', '충주시');

CREATE TABLE SIDO 
(
  SIDO_NO NUMBER NOT NULL 
, SIDO_NM VARCHAR2(6) 
, CONSTRAINT SIDO_PK PRIMARY KEY 
  (
    SIDO_NO 
  )
  ENABLE 
);

INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('1', '서울');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('2', '충남');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('3', '부산');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('4', '인천');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('5', '울산');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('6', '제주');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('7', '광주');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('8', '대전');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('9', '대구');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('10', '강원');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('11', '경북');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('12', '전북');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('13', '전남');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('14', '경기');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('15', '경남');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('16', '세종');
INSERT INTO "CODE_PEOPLE"."SIDO" (SIDO_NO, SIDO_NM) VALUES ('17', '충북');
